spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall-tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    database: 0
    host: localhost
    username:
    password: 123456
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: http://localhost:9200
logging:
  level:
    com.fxytb.malltiny.dao.*: DEBUG
mybatis:
  mapper-locations:
    - classpath:mybatis/*.xml
    - classpath:mybatis/**/*.xml
springfox:
  documentation:
    enabled: true
    open-api:
      enabled: false
    swagger-ui:
      enabled: true
# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
security:
  ignore:
    urls:
      - "/"
      - "/swagger-ui/"
      - "/*.html"
      - "/favicon.ico"
      - "/**/*.html"
      - "/**/*.js"
      - "/swagger-resource/**"
      - "v2/api-docs/**"
      - "/v2/api-docs"
      - "/swagger-resources/configuration/ui"
      - "/swagger-resources"
      - "/swagger-resources/configuration/security"
      - "/swagger-ui.html"
      - "/swagger-ui/swagger-ui.css"
